#! /bin/bash
nohup node ./Public/resCreate/api/bin/www21.js &
nohup node ./Public/resCreate/api/bin/www22.js &
nohup node ./Public/resCreate/api/bin/www23.js &
nohup node ./Public/resCreate/api/bin/www24.js &
nohup node ./Public/resCreate/api/bin/www25.js &
nohup node ./Public/resCreate/api/bin/www26.js &
nohup node ./Public/resCreate/api/bin/www27.js &
nohup node ./Public/resCreate/api/bin/www28.js &
nohup node ./Public/resCreate/api/bin/www29.js &
nohup node ./Public/resCreate/api/bin/www30.js &
nohup node ./Public/resCreate/api/bin/www31.js &
nohup node ./Public/resCreate/api/bin/www32.js &
nohup node ./Public/resCreate/api/bin/www33.js &
nohup node ./Public/resCreate/api/bin/www34.js &
nohup node ./Public/resCreate/api/bin/www35.js &
nohup node ./Public/resCreate/api/bin/www36.js &
nohup node ./Public/resCreate/api/bin/www37.js &
nohup node ./Public/resCreate/api/bin/www38.js &
nohup node ./Public/resCreate/api/bin/www39.js &
nohup node ./Public/resCreate/api/bin/www40.js &
